%include "stdint.i"
%include "replay_types.i"
%include "replay_shot.i"
%include "replay_frame_extractor.i"
%include "replay_buffer.i"
%include "replay_multiviewer.i"
%include "replay_preview.i"
%include "replay_playout.i"
%include "replay_ingest.i"
%include "replay_mjpeg_ingest.i"

